In [1]:
import pandas as pd
import os
import glob

In [2]:
import os

print(os.getcwd())

C:\Users\Gurnoor Singh\Desktop\olist-analysis

In [3]:
files = glob.glob("data/raw/*.csv")

for file in files:
    print(file)

data/raw\olist_customers_dataset.csv
data/raw\olist_geolocation_dataset.csv
data/raw\olist_orders_dataset.csv
data/raw\olist_order_items_dataset.csv
data/raw\olist_order_payments_dataset.csv
data/raw\olist_order_reviews_dataset.csv
data/raw\olist_products_dataset.csv
data/raw\olist_sellers_dataset.csv
data/raw\product_category_name_translation.csv

In [4]:
files = {
    "orders": "olist_orders_dataset.csv",
    "order_items": "olist_order_items_dataset.csv",
    "customers": "olist_customers_dataset.csv",
    "products": "olist_products_dataset.csv",
    "sellers": "olist_sellers_dataset.csv",
    "reviews": "olist_order_reviews_dataset.csv",
    "payments": "olist_order_payments_dataset.csv",
    "category_translation": "product_category_name_translation.csv",
    "geolocation": "olist_geolocation_dataset.csv"
}

data = {}

for name, file in files.items():
    data[name] = pd.read_csv(f"data/raw/{file}")

    print(f"{name}: {data[name].shape}")

orders: (99441, 8)
order_items: (112650, 7)
customers: (99441, 5)
products: (32951, 9)
sellers: (3095, 4)
reviews: (99224, 7)
payments: (103886, 5)
category_translation: (71, 2)
geolocation: (1000163, 5)

In [5]:
for name , df in data.items():
    print("_"*100)
    print(name)
    print("Shape :" , df.shape)
    print("Columns :" , list(df.columns))

____________________________________________________________________________________________________
orders
Shape : (99441, 8)
Columns : ['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']
____________________________________________________________________________________________________
order_items
Shape : (112650, 7)
Columns : ['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']
____________________________________________________________________________________________________
customers
Shape : (99441, 5)
Columns : ['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']
____________________________________________________________________________________________________
products
Shape : (32951, 9)
Columns : ['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']
____________________________________________________________________________________________________
sellers
Shape : (3095, 4)
Columns : ['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']
____________________________________________________________________________________________________
reviews
Shape : (99224, 7)
Columns : ['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']
____________________________________________________________________________________________________
payments
Shape : (103886, 5)
Columns : ['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']
____________________________________________________________________________________________________
category_translation
Shape : (71, 2)
Columns : ['product_category_name', 'product_category_name_english']
____________________________________________________________________________________________________
geolocation
Shape : (1000163, 5)
Columns : ['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

In [6]:
for name, df in data.items():
    print("_"*100)
    print(name)
    
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("\nMissing values:")
    print(df.isnull().sum())
    
    print("\nDuplicate rows:", df.duplicated().sum())

____________________________________________________________________________________________________
orders
Rows: 99441
Columns: 8

Missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
order_items
Rows: 112650
Columns: 7

Missing values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
customers
Rows: 99441
Columns: 5

Missing values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
products
Rows: 32951
Columns: 9

Missing values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
sellers
Rows: 3095
Columns: 4

Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
reviews
Rows: 99224
Columns: 7

Missing values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
payments
Rows: 103886
Columns: 5

Missing values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
category_translation
Rows: 71
Columns: 2

Missing values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate rows: 0
____________________________________________________________________________________________________
geolocation
Rows: 1000163
Columns: 5

Missing values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate rows: 261831

In [7]:
data["orders"].head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
data["order_items"].head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
data["customers"].head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
data["products"].head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [11]:
data["orders"].dtypes

order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

In [12]:
products = data["products"]

products[products["product_category_name"].isna()].head(10)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
244,e10758160da97891c2fdcbc35f0f031d,NaN,NaN,NaN,NaN,2200.0,16.0,2.0,11.0
294,39e3b9b12cd0bf8ee681bbc1c130feb5,NaN,NaN,NaN,NaN,300.0,16.0,7.0,11.0
299,794de06c32a626a5692ff50e4985d36f,NaN,NaN,NaN,NaN,300.0,18.0,8.0,14.0
347,7af3e2da474486a3519b0cba9dea8ad9,NaN,NaN,NaN,NaN,200.0,22.0,14.0,14.0
428,629beb8e7317703dcc5f35b5463fd20e,NaN,NaN,NaN,NaN,1400.0,25.0,25.0,25.0

In [13]:
products[products["product_category_name"].isna()].shape

(610, 9)

In [14]:
products[products["product_weight_g"].isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
8578,09ff539a621711667c43eba6a3bd8466,bebes,60.0,865.0,3.0,NaN,NaN,NaN,NaN
18851,5eb564652db742ff8f28759cd8d2652a,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
geo = data["geolocation"]

geo[geo.duplicated(keep=False)].sort_values(
    "geolocation_zip_code_prefix"
).head(15)

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
429,1001,-23.550498,-46.634338,sao paulo,SP
596,1001,-23.550498,-46.634338,sao paulo,SP
583,1001,-23.551337,-46.634027,sao paulo,SP
99,1001,-23.549292,-46.633559,sao paulo,SP
519,1001,-23.551337,-46.634027,sao paulo,SP
985,1001,-23.550498,-46.634338,sao paulo,SP
912,1001,-23.550498,-46.634338,sao paulo,SP
897,1001,-23.549292,-46.633559,sao paulo,SP
639,1001,-23.550498,-46.634338,sao paulo,SP
1246,1001,-23.549292,-46.633559,sao paulo,SP
1062,1001,-23.550498,-46.634338,sao paulo,SP
851,1001,-23.549825,-46.633970,sao paulo,SP
771,1001,-23.550498,-46.634338,sao paulo,SP
1004,1001,-23.549292,-46.633559,sao paulo,SP
206,1001,-23.550498,-46.634338,sao paulo,SP

In [16]:
geo["geolocation_zip_code_prefix"].nunique()

19015

In [17]:
for name in ["orders", "customers", "products", "sellers"]:
    df = data[name]
    print(
        name,
        "rows =", len(df),
        "unique IDs =", df.iloc[:, 0].nunique()
    )

orders rows = 99441 unique IDs = 99441
customers rows = 99441 unique IDs = 99441
products rows = 32951 unique IDs = 32951
sellers rows = 3095 unique IDs = 3095

In [18]:
customers = data["customers"]

print("Rows : " , len(customers))
print("Unique Customer_id : " , customers["customer_id"].nunique())
print("Unique Customer_unique_id : " , customers["customer_unique_id"].nunique())

customers.groupby("customer_unique_id")["customer_id"].nunique().value_counts()

Rows :  99441
Unique Customer_id :  99441
Unique Customer_unique_id :  96096

customer_id
1     93099
2      2745
3       203
4        30
5         8
6         6
7         3
9         1
17        1
Name: count, dtype: int64

In [19]:
orders = data["orders"]

print(orders["order_status"].value_counts())
orders["order_status"].value_counts(normalize = True) * 100

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

order_status
delivered      97.020344
shipped         1.113223
canceled        0.628513
unavailable     0.612423
invoiced        0.315765
processing      0.302692
created         0.005028
approved        0.002011
Name: proportion, dtype: float64

In [20]:
delivered_orders = orders[
    orders["order_status"] == "delivered"
]

In [21]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
dtypes: object(8)
memory usage: 6.1+ MB

In [22]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

orders[date_columns].head()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [23]:
for col in date_columns :
    orders[col] = pd.to_datetime(orders[col] , errors = "coerce")

orders[date_columns].dtypes

order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [24]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [25]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [26]:
# Delivery before purchase
print(
    "Customer delivery before purchase:",
    (orders["order_delivered_customer_date"] 
     < orders["order_purchase_timestamp"]).sum()
)

Customer delivery before purchase: 0

In [27]:
# Carrier pickup before purchase
print(
    "Carrier delivery before purchase:",
    (orders["order_delivered_carrier_date"] 
     < orders["order_purchase_timestamp"]).sum()
)

Carrier delivery before purchase: 166

In [28]:
# Estimated delivery before purchase
print(
    "Estimated delivery before purchase:",
    (orders["order_estimated_delivery_date"] 
     < orders["order_purchase_timestamp"]).sum()
)

Estimated delivery before purchase: 0

In [29]:
# Customer delivery before carrier delivery
print(
    "Customer delivery before carrier delivery:",
    (orders["order_delivered_customer_date"] 
     < orders["order_delivered_carrier_date"]).sum()
)

Customer delivery before carrier delivery: 23

In [30]:
carrier_issues = orders[
(orders["order_delivered_carrier_date"] 
     < orders["order_purchase_timestamp"])
]

carrier_issues[
 [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date",
        "order_estimated_delivery_date"
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
615,b9afddbdcfadc9a87b41a83271c3e888,delivered,2018-08-16 13:50:48,2018-08-16 14:05:13,2018-08-16 13:27:00,2018-08-24 14:58:37,2018-09-04
1111,ad133696906f6a78826daa0911b7daec,delivered,2018-06-15 15:41:22,2018-06-15 16:19:23,2018-06-15 14:52:00,2018-06-22 18:09:37,2018-07-18
1329,74e033208dc13a7b8127eb8e73d09b76,delivered,2018-05-02 10:48:44,2018-05-02 11:13:45,2018-05-02 09:49:00,2018-05-07 23:06:36,2018-05-29
1372,a6b58794fd2ba533359a76c08df576e3,delivered,2018-05-14 15:18:23,2018-05-14 15:33:35,2018-05-14 13:46:00,2018-05-19 19:33:32,2018-06-08
1864,5792e0b1c8c8a2bf53af468c9a422c88,delivered,2018-07-26 13:25:14,2018-07-26 13:35:14,2018-07-26 12:42:00,2018-07-30 14:45:02,2018-08-09
2760,c3eb293fd154223498b6551a728203e8,delivered,2018-07-19 14:06:04,2018-07-19 14:22:51,2018-07-19 13:49:00,2018-07-24 19:35:36,2018-08-06
3473,b0c2a7d04b165525254254a728c50a4e,delivered,2018-06-07 13:28:30,2018-06-07 13:57:22,2018-06-07 13:22:00,2018-06-21 17:36:43,2018-07-04
3661,2033a4586b5bec3229ebc1675a8ae092,delivered,2018-06-12 10:10:25,2018-06-12 10:39:59,2018-06-12 10:09:00,2018-06-19 14:08:27,2018-07-19
4114,08adcddad19d3acf37d1fa01cb9ded1e,delivered,2018-06-27 11:16:44,2018-06-27 11:30:56,2018-06-27 10:57:00,2018-06-29 17:39:53,2018-07-18
4159,dee6298ce7d1fb2645141ef9972157aa,shipped,2018-04-30 14:06:12,2018-04-30 14:15:24,2018-04-30 12:59:00,NaT,2018-05-28

In [31]:
delivery_issue = orders[
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"]
]

delivery_issue[
    [
        "order_id",
        "order_status",
        "order_purchase_timestamp",
        "order_approved_at",
        "order_delivered_carrier_date",
        "order_delivered_customer_date"
    ]
].head(10)

,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date
6437,a1abeb653a4d4cd1e142ccb8c82cd069,delivered,2017-07-20 11:20:52,2017-07-21 06:43:14,2017-07-28 16:57:58,2017-07-25 19:32:56
9553,383aa8b2724fe452d9ccd9934a8c628b,delivered,2017-07-02 20:58:43,2017-07-02 21:10:20,2017-07-07 17:22:41,2017-07-06 14:27:51
13487,cb1134f9010d242e9515ad1c78ec0c39,delivered,2017-07-16 12:35:34,2017-07-18 06:03:50,2017-07-20 19:22:02,2017-07-19 14:13:28
14474,dceb62e8fa94b46006c9554fed743df0,delivered,2017-07-20 20:58:05,2017-07-22 11:45:11,2017-08-01 18:23:30,2017-07-26 18:09:10
19268,5f9d46795c3126674e52becb3a1a517f,delivered,2017-07-18 11:48:20,2017-07-18 12:03:29,2017-07-20 23:03:42,2017-07-20 18:52:41
21338,8c78d01de3a9009e23d6877a7cc9be20,delivered,2016-10-08 15:36:50,2016-10-08 18:13:44,2016-10-26 11:41:53,2016-10-25 17:51:46
22520,b27af682321527a6349f1761eb3f360c,delivered,2017-06-14 20:17:04,2017-06-14 20:30:08,2017-06-27 14:51:54,2017-06-26 15:45:35
25393,1cc3ae63caffff2d6c3ee3e78e074acf,delivered,2017-08-07 21:35:22,2017-08-08 21:45:15,2017-08-10 18:28:56,2017-08-10 18:05:38
25646,e37f11cae9985ca58f0b56f268720537,delivered,2017-07-26 11:46:34,2017-07-27 10:10:16,2017-08-01 18:17:47,2017-07-31 17:49:56
27470,fa3e37584f4fdb1ded0e0de700dfcb4e,delivered,2017-07-30 19:32:23,2017-07-30 19:45:09,2017-08-09 18:18:43,2017-08-01 21:13:01

In [32]:
carrier_issue = orders[
    orders["order_delivered_carrier_date"]
    < orders["order_purchase_timestamp"]
].copy()

carrier_issue["difference_hours"] = (
    carrier_issue["order_purchase_timestamp"]
    - carrier_issue["order_delivered_carrier_date"]
).dt.total_seconds() / 3600

carrier_issue["difference_hours"].describe()

count     166.000000
mean       26.039478
std       318.923845
min         0.006667
25%         0.234444
50%         0.599861
75%         1.017500
max      4109.098056
Name: difference_hours, dtype: float64

In [33]:
delivery_issue = orders[
    orders["order_delivered_customer_date"]
    < orders["order_delivered_carrier_date"]
].copy()

delivery_issue["difference_hours"] = (
    delivery_issue["order_delivered_carrier_date"]
    - delivery_issue["order_delivered_customer_date"]
).dt.total_seconds() / 3600

delivery_issue["difference_hours"].describe()

count     23.000000
mean      78.455133
std       89.308070
min        0.388333
25%       23.338333
50%       39.864444
75%      128.759028
max      386.308056
Name: difference_hours, dtype: float64

In [34]:
carrier_issue["order_status"].value_counts()

order_status
delivered    165
shipped        1
Name: count, dtype: int64

In [35]:
delivery_issue["order_status"].value_counts()

order_status
delivered    23
Name: count, dtype: int64

In [36]:
delivered_orders = orders[
    orders["order_status"] == "delivered"
].copy()

delivered_orders = delivered_orders[
    delivered_orders["order_delivered_carrier_date"]
    >= delivered_orders["order_purchase_timestamp"]
]

delivered_orders = delivered_orders[
    delivered_orders["order_delivered_customer_date"]
    >= delivered_orders["order_delivered_carrier_date"]
]

In [37]:
products = data["products"]

print(products.isnull().sum())

print(products[products["product_category_name"].isna()].head())

print(products[products["product_weight_g"].isna()])

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
                           product_id product_category_name  \
105  a41e356c76fab66334f36de622ecbd3a                   NaN
128  d8dee61c2034d6d075997acef1870e9b                   NaN
145  56139431d72cd51f19eb9f7dae4d1617                   NaN
154  46b48281eb6d663ced748f324108c733                   NaN
197  5fb61f482620cb672f5e586bb132eae9                   NaN

     product_name_lenght  product_description_lenght  product_photos_qty  \
105                  NaN                         NaN                 NaN
128                  NaN                         NaN                 NaN
145                  NaN                         NaN                 NaN
154                  NaN                         NaN                 NaN
197                  NaN                         NaN                 NaN

     product_weight_g  product_length_cm  product_height_cm  product_width_cm
105             650.0               17.0               14.0              12.0
128             300.0               16.0                7.0              20.0
145             200.0               20.0               20.0              20.0
154           18500.0               41.0               30.0              41.0
197             300.0               35.0                7.0              12.0
                             product_id product_category_name  \
8578   09ff539a621711667c43eba6a3bd8466                 bebes
18851  5eb564652db742ff8f28759cd8d2652a                   NaN

       product_name_lenght  product_description_lenght  product_photos_qty  \
8578                  60.0                       865.0                 3.0
18851                  NaN                         NaN                 NaN

       product_weight_g  product_length_cm  product_height_cm  \
8578                NaN                NaN                NaN
18851               NaN                NaN                NaN

       product_width_cm
8578                NaN
18851               NaN

In [38]:
products["product_category_name"] = products["product_category_name"].fillna("unknown")

In [39]:
products.isna().sum()

product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [40]:
print("Product categories:", products["product_category_name"].nunique())
print("Translated categories:", data["category_translation"]["product_category_name"].nunique())

Product categories: 74
Translated categories: 71

In [41]:
missing_translation = set(products["product_category_name"]) - set(data["category_translation"]["product_category_name"])

print("Missing_translation num : " , len(missing_translation))
print(missing_translation)

Missing_translation num :  3
{'unknown', 'portateis_cozinha_e_preparadores_de_alimentos', 'pc_gamer'}

In [42]:
reviews = data["reviews"]

print(reviews["review_score"].value_counts().sort_index())

review_score
1    11424
2     3151
3     8179
4    19142
5    57328
Name: count, dtype: int64

In [43]:
print("Rows:", len(reviews))
print("Unique review_id:", reviews["review_id"].nunique())
print("Unique order_id:", reviews["order_id"].nunique())

Rows: 99224
Unique review_id: 98410
Unique order_id: 98673

In [44]:
review_id_counts = reviews["review_id"].value_counts()

print(review_id_counts[review_id_counts > 1].head(10))

review_id
08528f70f579f0c830189efc523d2182    3
c444278834184f72b1484dfe47de7f97    3
39b4603793c1c7f5f36d809b4a218664    3
44e9f871226d8a130de3fc39dfbdf0c5    3
1fb4ddc969e6bea80e38deec00393a6f    3
2d6ac45f859465b5c185274a1c929637    3
f4bb9d6dd4fb6dcc2298f0e7b17b8e1e    3
2172867fd5b1a55f98fe4608e1547b4b    3
32415bbf6e341d5d517080a796f79b5c    3
7b606b0d57b078384f0b58eac1d41d78    3
Name: count, dtype: int64

In [45]:
print(
    reviews[reviews["review_id"].isin(
        review_id_counts[review_id_counts > 1].index
    )].sort_values("review_id").head(20)
)

                              review_id                          order_id  \
46678  00130cbe1f9d422698c812ed8ded1919  dfcdfc43867d1c1381bfaf62d6b9c195
29841  00130cbe1f9d422698c812ed8ded1919  04a28263e085d399c97ae49e0b477efa
90677  0115633a9c298b6a98bcbe4eee75345f  78a4201f58af3463bdab842eea4bc801
63193  0115633a9c298b6a98bcbe4eee75345f  0c9850b2c179c1ef60d2855e2751d1fa
92876  0174caf0ee5964646040cd94e15ac95e  f93a732712407c02dce5dd5088d0f47b
57280  0174caf0ee5964646040cd94e15ac95e  74db91e33b4e1fd865356c89a61abf1f
54832  017808d29fd1f942d97e50184dfb4c13  8daaa9e99d60fbba579cc1c3e3bfae01
99167  017808d29fd1f942d97e50184dfb4c13  b1461c8882153b5fe68307c46a506e39
20621  0254bd905dc677a6078990aad3331a36  5bf226cf882c5bf4247f89a97c86f273
96080  0254bd905dc677a6078990aad3331a36  331b367bdd766f3d1cf518777317b5d9
89712  0288d42bef3dfe36930740c9588a570f  33d8795f04dd631f3480d7aaf90da3dc
94851  0288d42bef3dfe36930740c9588a570f  f889a5a0b44adc29c5465b99395ac3c1
47495  02aa7f5f75e964e3c7efa59a1f515281  d8e17d5f7dacf0970d316e7c03e741e8
95860  02aa7f5f75e964e3c7efa59a1f515281  db92613c074f00e53066388d48ad7512
71165  034528cb00b6bc981847acafbdf2ae0b  e1e8e3bca903de27e9a1c72b5a5795e0
81094  034528cb00b6bc981847acafbdf2ae0b  3d3742a96f24a8fe4e2e57628807e476
1988   03a6a25db577d0689440933055111897  2acfdc5131ff2cf4433e668454c9784c
9013   03a6a25db577d0689440933055111897  3fde8b7313af6b37b84b5c7594d7add0
21587  0467560f511c516ddaa54a60edb0c291  0c995611a99f81268d859184a416f1db
24901  0467560f511c516ddaa54a60edb0c291  55b2e390d5d80ada31ad1b795ebeb087

       review_score review_comment_title  \
46678             1                  NaN
29841             1                  NaN
90677             5                  NaN
63193             5                  NaN
92876             1                  NaN
57280             1                  NaN
54832             5                  NaN
99167             5                  NaN
20621             1                  NaN
96080             1                  NaN
89712             3                  NaN
94851             3                  NaN
47495             3                  NaN
95860             3                  NaN
71165             1                  NaN
81094             1                  NaN
1988              5                  NaN
9013              5                  NaN
21587             5                  NaN
24901             5                  NaN

                                  review_comment_message review_creation_date  \
46678  O cartucho "original HP" 60XL não é reconhecid...  2018-03-07 00:00:00
29841  O cartucho "original HP" 60XL não é reconhecid...  2018-03-07 00:00:00
90677                                                NaN  2017-09-21 00:00:00
63193                                                NaN  2017-09-21 00:00:00
92876  Produto entregue dentro de embalagem do fornec...  2018-03-07 00:00:00
57280  Produto entregue dentro de embalagem do fornec...  2018-03-07 00:00:00
54832                                                NaN  2018-03-02 00:00:00
99167                                                NaN  2018-03-02 00:00:00
20621  O pedido consta de 2 produtos e até agora rece...  2017-09-09 00:00:00
96080  O pedido consta de 2 produtos e até agora rece...  2017-09-09 00:00:00
89712                                                NaN  2017-07-29 00:00:00
94851                                                NaN  2017-07-29 00:00:00
47495                                                NaN  2017-07-27 00:00:00
95860                                                NaN  2017-07-27 00:00:00
71165                                                NaN  2017-05-14 00:00:00
81094                                                NaN  2017-05-14 00:00:00
1988   Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...  2017-12-15 00:00:00
9013   Muito Bom! Gostei Bastante! Tecido Ótimo! Aten...  2017-12-15 00:00:00
21587                                                NaN  2017-02-09 00:00:00
24901                                                NaN  2017-02-09 00:00:00

      review_answer_timestamp
46678     2018-03-20 18:08:23
29841     2018-03-20 18:08:23
90677     2017-09-26 03:27:47
63193     2017-09-26 03:27:47
92876     2018-03-08 03:00:53
57280     2018-03-08 03:00:53
54832     2018-03-05 01:43:30
99167     2018-03-05 01:43:30
20621     2017-09-13 09:52:44
96080     2017-09-13 09:52:44
89712     2017-07-31 17:11:04
94851     2017-07-31 17:11:04
47495     2017-07-29 15:09:50
95860     2017-07-29 15:09:50
71165     2017-05-15 02:17:38
81094     2017-05-15 02:17:38
1988      2017-12-16 01:32:18
9013      2017-12-16 01:32:18
21587     2017-02-14 15:58:44
24901     2017-02-14 15:58:44

In [46]:
order_review_counts = reviews["order_id"].value_counts()

print(order_review_counts[order_review_counts > 1].head(10))
print("Sum " , order_review_counts[order_review_counts > 1].sum())

order_id
df56136b8031ecd28e200bb18e6ddb2e    3
c88b1d1b157a9999ce368f218a407141    3
03c939fd7fd3b38f8485a0f95798f1f6    3
8e17072ec97ce29f0e1f111e598b0c85    3
d04aa7a56c20579debaf2cd69ce4dd73    2
029863af4b968de1e5d6a82782e662f5    2
29062384ce4975f78aeba6a496510386    2
bbf6a647ecc68aa5e79d2cd75ef44c68    2
7f13a20e25350f4a55fb2a7c9a2e8d88    2
aef2bc3845eb581cecce74b769d46c6a    2
Name: count, dtype: int64
Sum  1098

In [47]:
data["payments"].describe(include = "all")

,order_id,payment_sequential,payment_type,payment_installments,payment_value
count,103886,103886.000000,103886,103886.000000,103886.000000
unique,99440,NaN,5,NaN,NaN
top,fa65dad1b0e818e3ccc5cb0e39231352,NaN,credit_card,NaN,NaN
freq,29,NaN,76795,NaN,NaN
mean,NaN,1.092679,NaN,2.853349,154.100380
std,NaN,0.706584,NaN,2.687051,217.494064
min,NaN,1.000000,NaN,0.000000,0.000000
25%,NaN,1.000000,NaN,1.000000,56.790000
50%,NaN,1.000000,NaN,1.000000,100.000000
75%,NaN,1.000000,NaN,4.000000,171.837500
max,NaN,29.000000,NaN,24.000000,13664.080000

In [48]:
print(data["payments"].isnull().sum())
print("_"*100)
print(data["payments"].shape)
print("_"*100)
print("Duplicated Rows : " , data["payments"].duplicated().sum())

order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
____________________________________________________________________________________________________
(103886, 5)
____________________________________________________________________________________________________
Duplicated Rows :  0

In [49]:
data["payments"].nunique()

order_id                99440
payment_sequential         29
payment_type                5
payment_installments       24
payment_value           29077
dtype: int64

In [50]:
payments = data["payments"]

payment_order_id_count = payments["order_id"].value_counts()

print(payment_order_id_count[payment_order_id_count > 1].head())
print("_"*100)
print(payment_order_id_count[payment_order_id_count > 1].sum())

order_id
fa65dad1b0e818e3ccc5cb0e39231352    29
ccf804e764ed5650cd8759557269dc13    26
285c2e15bebd4ac83635ccc563dc71f4    22
895ab968e7bb0d5659d16cd74cd1650c    21
ee9ca989fc93ba09a6eddc250ce01742    19
Name: count, dtype: int64
____________________________________________________________________________________________________
7407

In [51]:
payments["payment_sequential"].value_counts()

payment_sequential
1     99360
2      3039
3       581
4       278
5       170
6       118
7        82
8        54
9        43
10       34
11       29
12       21
13       13
14       10
15        8
17        6
19        6
18        6
16        6
20        4
21        4
22        3
24        2
25        2
26        2
23        2
27        1
28        1
29        1
Name: count, dtype: int64

In [52]:
payments["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [53]:
payments_0 = payments["payment_value"]

print(payments[payments_0 == 0])
print(payments_0[payments_0 == 0].value_counts())

                                order_id  payment_sequential payment_type  \
19922   8bcbe01d44d147f901cd3192671144db                   4      voucher
36822   fa65dad1b0e818e3ccc5cb0e39231352                  14      voucher
43744   6ccb433e00daae1283ccc956189c82ae                   4      voucher
51280   4637ca194b6387e2d538dc89b124b0ee                   1  not_defined
57411   00b1cb0320190ca0daa2c88b35206009                   1  not_defined
62674   45ed6e85398a87c253db47c2d9f48216                   3      voucher
77885   fa65dad1b0e818e3ccc5cb0e39231352                  13      voucher
94427   c8c528189310eaa44a745b8d9d26908b                   1  not_defined
100766  b23878b3e8eb4d25a158f57d96331b18                   4      voucher

        payment_installments  payment_value
19922                      1            0.0
36822                      1            0.0
43744                      1            0.0
51280                      1            0.0
57411                      1            0.0
62674                      1            0.0
77885                      1            0.0
94427                      1            0.0
100766                     1            0.0
payment_value
0.0    9
Name: count, dtype: int64

In [54]:
payment_record = payments["payment_type"].value_counts()
print(payment_record)

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

In [55]:
payment_seq = payments[payments["payment_sequential"] > 2]

payment_seq["payment_type"].value_counts()

payment_type
voucher        1485
credit_card       1
debit_card        1
Name: count, dtype: int64

In [56]:
payments[payments["payment_sequential"] == 29]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26

In [57]:
payments[payments["order_id"] == "fa65dad1b0e818e3ccc5cb0e39231352" ]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
4885,fa65dad1b0e818e3ccc5cb0e39231352,27,voucher,1,66.02
9985,fa65dad1b0e818e3ccc5cb0e39231352,4,voucher,1,29.16
14321,fa65dad1b0e818e3ccc5cb0e39231352,1,voucher,1,3.71
17274,fa65dad1b0e818e3ccc5cb0e39231352,9,voucher,1,1.08
19565,fa65dad1b0e818e3ccc5cb0e39231352,10,voucher,1,12.86
23074,fa65dad1b0e818e3ccc5cb0e39231352,2,voucher,1,8.51
24879,fa65dad1b0e818e3ccc5cb0e39231352,25,voucher,1,3.68
28330,fa65dad1b0e818e3ccc5cb0e39231352,5,voucher,1,0.66
29648,fa65dad1b0e818e3ccc5cb0e39231352,6,voucher,1,5.02
32519,fa65dad1b0e818e3ccc5cb0e39231352,11,voucher,1,4.03
36822,fa65dad1b0e818e3ccc5cb0e39231352,14,voucher,1,0.00
39108,fa65dad1b0e818e3ccc5cb0e39231352,29,voucher,1,19.26
39111,fa65dad1b0e818e3ccc5cb0e39231352,28,voucher,1,29.05
63369,fa65dad1b0e818e3ccc5cb0e39231352,15,voucher,1,14.04
65641,fa65dad1b0e818e3ccc5cb0e39231352,3,voucher,1,2.95
68853,fa65dad1b0e818e3ccc5cb0e39231352,8,voucher,1,26.02
73537,fa65dad1b0e818e3ccc5cb0e39231352,12,voucher,1,3.60
74239,fa65dad1b0e818e3ccc5cb0e39231352,21,voucher,1,4.11
74721,fa65dad1b0e818e3ccc5cb0e39231352,19,voucher,1,5.02
77885,fa65dad1b0e818e3ccc5cb0e39231352,13,voucher,1,0.00
78050,fa65dad1b0e818e3ccc5cb0e39231352,16,voucher,1,12.86
79587,fa65dad1b0e818e3ccc5cb0e39231352,26,voucher,1,28.27
79670,fa65dad1b0e818e3ccc5cb0e39231352,17,voucher,1,3.72
80321,fa65dad1b0e818e3ccc5cb0e39231352,18,voucher,1,0.73
82593,fa65dad1b0e818e3ccc5cb0e39231352,7,voucher,1,0.32
85166,fa65dad1b0e818e3ccc5cb0e39231352,23,voucher,1,18.86
93337,fa65dad1b0e818e3ccc5cb0e39231352,20,voucher,1,150.00
99213,fa65dad1b0e818e3ccc5cb0e39231352,24,voucher,1,0.42
100606,fa65dad1b0e818e3ccc5cb0e39231352,22,voucher,1,4.03

In [58]:
payments["payment_installments"].value_counts()

payment_installments
1     52546
2     12413
3     10461
4      7098
10     5328
5      5239
8      4268
6      3920
7      1626
9       644
12      133
15       74
18       27
11       23
24       18
20       17
13       16
14       15
17        8
16        5
21        3
0         2
22        1
23        1
Name: count, dtype: int64

In [59]:
payments["payment_installments"].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [60]:
payment_0 = payments["payment_installments"]

payments[payment_0 == 0]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
46982,744bade1fcf9ff3f31d860ace076d422,2,credit_card,0,58.69
79014,1a57108394169c0b47d8f876acc9ba2d,2,credit_card,0,129.94

In [61]:
data["orders"].nunique()

order_id                         99441
customer_id                      99441
order_status                         8
order_purchase_timestamp         98875
order_approved_at                90733
order_delivered_carrier_date     81018
order_delivered_customer_date    95664
order_estimated_delivery_date      459
dtype: int64

In [62]:
data_missing = set(data["orders"]["order_id"]) - set(data["payments"]["order_id"])
print(data_missing)

orders[orders["order_id"] == "bfbd0f9bdef84302105ad712db648a6c"]

{'bfbd0f9bdef84302105ad712db648a6c'}

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04

In [63]:
data["order_items"]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14
...,...,...,...,...,...,...,...
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [64]:
#how many unique orders in order_items

print(data["order_items"].nunique())
data["order_items"]

order_missing = set(data["orders"]["order_id"]) - set(data["order_items"]["order_id"])
order_missing

order_id               98666
order_item_id             21
product_id             32951
seller_id               3095
shipping_limit_date    93318
price                   5968
freight_value           6999
dtype: int64

{'0010dedd556712d7bb69a19cb7bbd37a',
 '00a500bc03bc4ec968e574c2553bed4b',
 '00b1cb0320190ca0daa2c88b35206009',
 '00bca4adac549020c1273714d04d0208',
 '00d0ffd14774da775ac832ba8520510f',
 '00daac8efd71674d62356c2a306d1e4c',
 '0130f0f71fb0e831d18e6a3b33a3a50c',
 '016706d732e79b49035275c048edb2c4',
 '01cb6d702e5233235f4125309d184bf4',
 '02bfe71c2bbd56f6de9c2c357adff45c',
 '02de1e44936e56ddc1621c46d86bf91e',
 '02e723e8edb4a123d414f56cc9c4665e',
 '03227bf7c543bbee4efa38bb6c6763c8',
 '032cf17f7a713287e46999fddea6051b',
 '03310aa823a66056268a3bab36e827fb',
 '037a9cf279c376ab222c9d27be892513',
 '03d1edbd314ca7682ec0f3e67d3763e2',
 '04770bff63a120fbf0eea1f62b84f8f0',
 '04a2ba381317648726f46210a46ece95',
 '04b8c60eb3cceaecde917716daa30bde',
 '05c852fbe20c108caf9f479633cbe088',
 '05da04fd9f94dfb49fd643216d2cbe1f',
 '05e8a1fd3d354369a3de6e7230a3651f',
 '0623dbbd06c0d4059dbfefab8748a491',
 '0667c8670e40ad2783c71d45ceb361e0',
 '075cc7ce268544c780299db653d21467',
 '084d2c70d33f8b9a1e21393471844591',
 '08662c478bed0444d0515925af759547',
 '08ea65e91550ee222548404d16eb06b4',
 '08ee9c1b1da47ffd2a7c7163aa134b16',
 '091deda616c370d63f0bf9a3f525fb34',
 '0990477f1481cdf40c00d57bb13a1c9b',
 '09f541f117ac3f665dc3aad6d3bb8fc9',
 '0a472c47d928bf4cd8b6a7a30345eeb7',
 '0a5c74ccc786ced7903270de9d6c170a',
 '0a6b7c79b8c67dedc51f2dea7b4e1e59',
 '0b398dbb3e7c81005f3c69b01488c4c9',
 '0bde826daa0bd10393e958cf5d69dd26',
 '0cafd6a7576a6aae0f891008a87f1546',
 '0cb3c0cb279f04b99a10ac141fa8586f',
 '0cb763300f5679bee73a0b0fdfe0a2d2',
 '0cfc5b8b63bf71f738f96e68adb96b3d',
 '0d2c1a413f6aa3a36b8bb940b028f930',
 '0d3adebce4bebc1f80a7f36e9833f497',
 '0da43144c61f413957a7e7c8b2555dad',
 '0e64b89242bbb62b8ea29c57fc8073fb',
 '0e6b2d0fe443a6d38c0f6447f4eb2262',
 '0e6dbbc7484dc1ee0392c9ca801035c2',
 '0ea5760bfbfe671160e0599cf68f1981',
 '0f3b2951a363f6a201ad23e3ce2c0313',
 '0fb9645c128ac84788798f0129496ca7',
 '10a045cdf6a5650c21e9cfeb60384c16',
 '10e080f0e43ef41f43b9ff6da4451835',
 '115b01b1f77f0e02812425b6f5cd8f2f',
 '11c71300049cd2c9896b0be33f04d574',
 '123e27a1a4d0b2481d8618ac3dff7d4e',
 '127f8f54e84665683a3c9bde5b3e768c',
 '129ea9ae4b85283decb23ea1756f505d',
 '12e5a909c18964acada1ce9a760d9afe',
 '151e44f3dd461fe0838b6f59f884749f',
 '15ec3d48383c58c0dc96cd66f8884630',
 '1612081119e8f23745698ad3367cc14b',
 '16b8c07980cc1e47a31ebb35d9222807',
 '1762aa0ce22469c003348a42e46f5269',
 '1768e7971ac449abce2917f608c8a69f',
 '1770ee9dc600eccda7bfb6c56562b91d',
 '1800254c5ad71baad5c53866d4ed0ea0',
 '1857e77a4bad8abb2db929f107430663',
 '186d3cd768be1890d832106f914ba37c',
 '18c528b07b50f67122420d4b645dc84c',
 '190cce77a8a1f436ff7bb2e684906449',
 '1982a20c2a9d116da964e488d59eebe7',
 '1985dcd0eb8cb683615c1d2b8f324572',
 '19bb130ea3cc2dab25b3bcf2097aa462',
 '19bbda1f882b3aeddba973e935519905',
 '19bf02099b31db3f2f5d1bfb4fbf49c4',
 '19d3484384a0e1eef23357b8c193bd86',
 '1a41f24ba682e06e82dd1ce5f77b6f5e',
 '1a5d21f44c73693b9930d0ca33a9d0b1',
 '1aba68837cfafa9cc4bba58efee87d4a',
 '1ad22e16129698e1a3cc11e4350d2cb7',
 '1aecadf4362edaca7fa033e882076c8d',
 '1c2c24a58f6335fa1dbda79cf2ebff74',
 '1c3a814fa046dc2f684276b1ca26786e',
 '1c7c8ab324927f5b6e52338bd110bef4',
 '1c851b2d3587fe02888b58c64fbc1ab0',
 '1ce8144d59eef2763c0fbaf8ffd26d31',
 '1dbe2e0c5594a384eac781a7e46c6011',
 '1ddedd282e921efe5e3e931f5a1369d9',
 '1e4dc51447faa970879bb120932eebb6',
 '1e792fcdefb0bb34325cdc1dee84fcea',
 '1e9cdb2ee26ee17ecb5f050a180cf8ff',
 '1f0a1cc0dc294f24707a0167df26c94b',
 '1f5833c59dc618d2d3b9072f51195d16',
 '1f66f9bfd244a5383aeb00a84ad12a66',
 '1fda9a8d1632a5964c43fb8e64dbe3e3',
 '1ff6183537eb3a189de77b309ed28ad1',
 '20085191cbcabee83a2016eb4a9fbf21',
 '2015fdddda0f27eaf4ebdf451d70a41e',
 '208edba34ba9cf8d8f603672e1966b75',
 '20e297eefc937e9b79e2cf97e9faddf1',
 '20ff9b4b339b20ef47cfcda736a17a52',
 '21a00b08cbeb5716bbb66105e3dbd850',
 '227c804e2a44760671a6a5697ea549e4',
 '232674aa2334edfdd9c2dbe346291712',
 '236e6ec6171c1870d4bcf4ccfad87f49',
 '23fdd0e16ad79ceab4e5f407772d64fa',
 '2411e5019928e883d049f7242362c23b',
 '2429083883078c31cf2337ce0dd425ee',
 '2463e85fc460252cacb332c69099f298',
 '24b425b6d0f061fcb84c1832d221e3bb',
 '24cee263ae15271412b77854eb10b840',
 '24f686e03e134195c83dc3e2b6bf4cd0',
 '252788350f9dad30b31847845fe119fe',
 '2559552ea70a7caa245eca67f410a3f4',
 '259fe605870f08ddf83ebb61f204b9e1',
 '261e56a43de07e1b1bc9e8615c8e8aa9',
 '2636a02ee7de9590df86a4c24b739c49',
 '2636c69e57fce1b3a556b70f1acd1192',
 '2663ce3526465b7ee9809428adabdc45',
 '269507123b136cce3d2f6c5915f11bad',
 '27667a063cb59b5d987a5a71c192cce5',
 '27b7289530871ba2c68509ec562b1544',
 '2867faaa7a912bbc2bf8d8e40d7a0354',
 '29380cfab5f9f5f233e2c71e16cadc68',
 '294b367987f073eb316ecef17f1078a0',
 '294bc47f2c556ebbec32a74c4811efd5',
 '29557adf1f00504612cbebf82c843d77',
 '295f0c892077fab482adb25cfc37aa79',
 '2982a4a9b9ff0bf9a4f5b88a45a6fa67',
 '298b961b82fd30c53433ae821ba75aa9',
 '2b0edc4c59d83dcef85466718c36a317',
 '2b25bdbc985fdd953cced7c3fdf0a2fe',
 '2b3d870a4d670c91f15668cea4fe3aa5',
 '2b68bb35779189904b0cd730eaba3d1d',
 '2b941f8e6ff81158a52de44909dc2a52',
 '2bb02fdf5637a68cd5d13c78c37c3376',
 '2c44ef48e157c9a43e9998da9a3248bd',
 '2c885b285dce307562d7f4caae89c6dc',
 '2c990009034e1fc83904584b26b5fd25',
 '2c9c2c96702997c879d75f927b76165e',
 '2ce9683175cdab7d1c95bcbb3e36f478',
 '2d31315ad8289e1e63c8451715e80306',
 '2d57932a94a64e0729ec5b88b4860d0d',
 '2dd5bcfb8c66b22a80ffe45078eb2a99',
 '2ddc0120a9ee5d965a08b68f6a3e2885',
 '2de47e473306065fb0cd0322d8d9952b',
 '2e287cee637969033ec9ab49602e61ef',
 '2e3c6e30c69763a7dfe40f11a19ed3da',
 '2e935fa1d39497aa0ec3f1107fbfb5b8',
 '2e9d8db9e132a9b5e1236618b7e8ef4a',
 '2ec030d65d7742d4afb8df93dd86ba76',
 '2f30c0b1905c65a8ff6c6358bc909625',
 '2f346d92b11fcc7c342b3392b174cf3b',
 '2f5124f516a7f5e4095ef4325d67c511',
 '2f634e2cebf8c0283e7ef0989f77d217',
 '2fa565240e8353e7a1ad78347f8608fa',
 '2ff205d5135b1c7763c6561d2643df51',
 '30945faa37e8264ea2815f7bf799adf0',
 '309688f286ca9fb39735664ba1e37b29',
 '30a3bac324f40459c6d1a739bc811506',
 '30cdf125a8d4f89d00dee4b9af9194ee',
 '30e0a586733725ef792f50d33720b961',
 '31a1a43e09fe1f26cdcb077099cadf82',
 '31b91033dcb0502e616f40ced16dccc6',
 '31c672e3859d5d55d460ea8dbc39053d',
 '31c6c41e2949f1a20c6f8e60ac17d4fe',
 '31f935babbc97f5990e0ffd128e19541',
 '3257d333ee8b3f21786b6270940d1fd4',
 '32b5ca23bd0b8761a4e3c0fb0b4b4418',
 '32bc13d17332ed4f07e360611c146b87',
 '32c75dfb830b25a968cfd39e54d315a3',
 '32cf225a72e589313cd8d967203effc6',
 '335f8f913a1d29120e07b6bb9847d73c',
 '33c4ff80921c70a563083f3e317f7247',
 '33d8795f04dd631f3480d7aaf90da3dc',
 '33e13c48e5883f2a3ae2269bf57650c7',
 '33f11b444d480cee508b54f3cf17b079',
 '33fe1cb532ac16a48902980e00c26da6',
 '342505ef4323f0572eda009be6080f6c',
 '3438960569bf3e42fa63f8e7bab0ac03',
 '34cea4a1fdf5fefdf4d48d7dafe53911',
 '35dc5c3a87f9e9cf93676b98d4bc35a2',
 '35de4050331c6c644cddc86f4f2d0d64',
 '36be874974d3616f9a1a763d0ac1d655',
 '36cde427894b4797db8316e92b8e58f2',
 '3716cd16bc2a97768309209eb4d4c6a7',
 '37553832a3a89c9b2db59701c357ca67',
 '37af1b25e7710f09d122aaf3f8b68114',
 '383bb8b07361166ea86f3f4b51e96ff7',
 '3859aef969659dcc5439967f8ffbbc07',
 '38a86eb53c2309d6234fc9bad96331ac',
 '392ed9afd714e3c74767d0c4d3e3f477',
 '3a0b1b5c52367a68f9deab55f3464a14',
 '3a0fbe8fbdae776394cd93385366a4fd',
 '3a3aed58b078ba2d2105cd76ce7a76d7',
 '3a3cddda5a7c27851bd96c3313412840',
 '3a40d639b7d8167f255bbb2b7372cddd',
 '3b090f7fe6e2cf01b468a154dc9c546a',
 '3b4b5ec89dc09c7aedc74199be65fef7',
 '3bb3f7783f2e72ad6c1baacfdc807994',
 '3bd3b4d482f916c2c9662b8da6f2758b',
 '3c3df3dd2afaabb39a53131f9ce98116',
 '3c8702d3b056de079d6cdd6ee1ffeb55',
 '3ccf1aa4144993ddec8287ef8ee0a107',
 '3cd41dc7c9fceb7de4fb0e9983a4b1ed',
 '3e7ca74af2e30d9f16183f5c9d65ef85',
 '3f2467ae6b5a92494a59e95de0d79ba8',
 '3f6509ff22303ff04b9bf1b2c8bf69c6',
 '402e0a2ad64d2f2b8f0d06d436789aca',
 '40fd591202d04d78c987cfc6990ad237',
 '410d704bdcbe2893fd5ad73fe8166f43',
 '4188e271c401875d724b4e9ee6fe7206',
 '42202323e8e5319c107e361d55ad0de6',
 '4317fe882d992cda2fb3d51baeb2751c',
 '43c8d05a1478e794217ad3b39398022a',
 '43f15e122ae8ae3eda33bf64b011c085',
 '4493ce8729200aed0eca9d3ae8bcc57c',
 '44b4829b58167b697a69c8aa8eb64733',
 '453cabc3a3d6d0d80bd08d9eefb6a607',
 '453d6f15ae1c7406d6ec6a5ee3909b82',
 '45daa18f4e3e34c727128f6a775fff95',
 '4603cc4d4654635e3c16a1ac226036f4',
 '4608a27e9e60c05b054631def491e7af',
 '463270aee6f932c94319683e66e7e59d',
 '4637ca194b6387e2d538dc89b124b0ee',
 '4641a7999ca05850ee60509c213dc8ac',
 '46ac809c6b319398df696f5668806fee',
 '46c25d5c696b53935b00b3e3fa555d20',
 '46f36d95da75ced0462d57df904d36d0',
 '47282cfe5747c1c19920f090e491d285',
 '4748c7d66bbedbf52de84b3bc4cbc482',
 '47bd649b812fd8ecc28320c466974088',
 '484ce4bf2067023e5184d003c41eb07a',
 '489b43fc6f7840318ee5d83ee35b86c1',
 '48f2d0b950703bfb145b7c3c0641b4bb',
 '498081e5523106ea57b698fb881fb1c8',
 '49c5132b03e35ffa18fdca050d1f8e33',
 '4a0d049ee6c82b3348a21bb211c0a44d',
 '4a1c879db7056f078a037fdf72b6d0fc',
 '4a42846a6eed9d15714fe30181399f2a',
 '4a44e928d587e7cd7068ea354471c477',
 '4a5cf649e3eb500fc079aace5f03583e',
 '4a6c07557205c5dbdeae7e289af5c1c6',
 '4af4d191d7e83818829a9af9ea7fcdfc',
 '4b03319a5a065c83d4fcc4f18f8cb257',
 '4b3b5fc7398939e35a47fe5a8c0be5cb',
 '4b460251c3d2ba44dd61b0b6c3410ac6',
 '4bbe949608f669144f0db3f8cde75cd7',
 '4bd0d8aa4756f78245bd56015d4ddcc0',
 '4c8b9947280829d0a8b7e81cc249b875',
 '4cccc0d35e7c7a0dc766ad3c4043e33e',
 '4ce5e2d15628c2277ca6ed81ee60f9de',
 '4d59cc2a2e7bb6c0a851725f5888a9b5',
 '4ffaf2cdcc432ea3cd8ae0ab7a789cb0',
 '4ffd41fadb59bd398d869be78f1b2be3',
 '5034308872e3b0e7c30ab14859feef53',
 '503e8daafed23dbae78ff210f2d41f0f',
 '50428fc6ef58fd5cebf433ef7f06be0d',
 '50503051a38d8ee049d1226032c7d82d',
 '50bb0c134ee3365dd06e13da6cda15fe',
 '51192863a004d47d0e4f5bf5384bf88f',
 '51375acfdef4d742df94640aa60d385b',
 '51b00c5a9b0224f467f74d55424b4235',
 '51bda649419be0084a39cb53e9c6f262',
 '52267d8c7f4a0227294efd0ef23fcefb',
 '5226f1a731e8a1215da5e1bea64e2130',
 '5290c34bd38a8a095b885f13958db1e1',
 '52b7f26dd95604cb836ba17f96a6b056',
 '52dfaf3e430903d40571c0eb44d324b5',
 '52f308ce830731bfdfea4539e140073f',
 '52fd8c890356febe4f78b653ef130cd2',
 '52ffca67c47f7bc4350f82b1d2c20dec',
 '534a0fbe91a806a1dc6bf09b497e3d6f',
 '53ec902459673efbbcb34dec981931d3',
 '54b267f79786d7ac585ab0aac88d6da6',
 '54b56f2389dee113344da742da7890c9',
 '5517dcebf1ab177978bae7e7c66de1b6',
 '553fee3c21ab4328508c8e467806613e',
 '55aa287c6ca17e8c3262b9ef1e12fac6',
 '55f1a7153e4d67447465073ad9490f04',
 '569d43a54c364df5b367ab33e96eacf0',
 '572c4bbf0f5f85a9b4a2c4fe0c7f04d5',
 '574f906eedf477adaf3507222887d81f',
 '582fd4fa596ee1af88f153a5ba0523f2',
 '5837a2c844decae8a778657425f6d664',
 '596288a27579ad1fec1d704efe7d9ab7',
 '5965bbd72c3ca0d9634419437ca53897',
 '59798edc300f7563a9bdf18b2740def9',
 '5a00b4d35edffc56b825c3646a99ba9d',
 '5a14c8b3d919a4ef3f3428b0459c47b2',
 '5aac76cf7b07dd06fa4d50bf461d2f40',
 '5ae7a6fa175ab7b180b6c0142e5466e9',
 '5b9680f27b5067afded00b23f9cb4d61',
 '5bcdec60d84d4495d0d90b64a3e81804',
 '5bd5f0a2e24b51f1d1d6e855f9f03e3d',
 '5c4e4e1d3abaee058758731094e9a7cc',
 '5ca9d935dd5306bf85a2f1e263d058f1',
 '5d80dfb48f5c62fe1cbd194b1b6f57bd',
 '5d9e1e0e7084f2f9e90a7069e64cba61',
 '5e0eae0316373e1459c05b539e18f060',
 '5f2dbe00a1732133a6809ae1af554123',
 '5fabc81b6322c8443648e1b21a6fef21',
 '60260cf275316912451558bb743bbfc7',
 '607c1c3f926d9435d428d7aa7d52a1ed',
 '607cf95d7f8a8c1590f421fecdf0d95c',
 '60d7d8686099e4682199966963c66ae2',
 '6111350dd1f8b825ac82e9caea339f07',
 '616fa7d4871b87832197b2a137a115d2',
 '6178d892fe5eef77fb756aed59b758bd',
 '61839bad7238b99a645d22f47028722c',
 '61a86f238895780d1ddc6344985537ef',
 '61bc37c42c68767e75243b8c2061f5aa',
 '620b0acb9258b51defbc51804c5298d5',
 '62492d216bd7ca39cab1f24109b6bfd7',
 '629a524cbbd0a42a04f87ad39648d4ca',
 '6338011716bfe53b960847be47479662',
 '63802c52ced9ff923c962ecbf4b3a2a2',
 '642b39405abba96bc0e134680e8ceb02',
 '648637c544f762334d4ce9bbe88ebe21',
 '64a58e424494f1f8ed5895885b9dfe16',
 '651a89e11653d8df43a624a903fe0f5e',
 '65959cbdb267c29a5cb0021a367df75c',
 '65df8539acbce2e41ba3a4a3ce0a3470',
 '65f87722388463aa7d02023c8f5b11ab',
 '65fdcb432cb9cfa970e3a3817b39040d',
 '66cb680674721f9816e366a15a93633f',
 '66e4a36ff490014773971a6ee0b6a0e4',
 '670e3b20191d3198a76069c8f9b12355',
 '672ab3776d5b25e586521469609ae774',
 '675b0980a1c53e959dc721b6e608997f',
 '67b0f3d0a405fc007841f73f2792323b',
 '68664ce4c84bcf1e6682d90992c7504d',
 '6900ba78f72feb30643f7c2e2ebb3aa1',
 '69647a30e77959dbf0000636927c27d6',
 '69c49491c1300f416d32e8bedc9f8907',
 '69fd1a4dd8b96b9ab0dc82b95be21efd',
 '6a30e349ceba14fcd64f13c3fd62aed3',
 '6a91f55a2fad58d1b580326cd07f5795',
 '6ad57aecbae806a7e9cc2cdb6b380711',
 '6c0c4ed997d520a3b737650e43c8e042',
 '6c15888cd708d4c1487eb36753212d69',
 '6c16d886be4fe03174a289a4ca70a775',
 '6c4e764954bc530adac8b0842d8f1647',
 '6cf5c427fb11bc5fe8abefa86aa7ba0b',
 '6d3130927406da969ab807821a93a65d',
 '6d928ae5792f61a71bb3e3e528bf4a28',
 '6d97e3d5d9043bb4fa4f8fd0b4d9f230',
 '6d9bd9b4caa7d961a6d31427ad0e557e',
 '6dd0cc64fed627388bf95943af884f70',
 '6e7e891760708803a2f4203981f2d69d',
 '6e7f938e1ebc4eb4b205b2ad66c5525d',
 '6e98de3a85c84ead6689189b825d35b5',
 '6ec704c9a120baaa6b3e162255ec684b',
 '6f04a69509e62866b1837e6a4f22c47f',
 '6f3772f092a98dfbb37265f3186ba374',
 '7018a2cb4802de2f9ed4b09b6a98e6fd',
 '7159096c5aa9be77f7f0c26c01ee9793',
 '72fa449394ed9dc9093819f93ca563af',
 '72fcdcc4d106595993b31fc91c800113',
 '735458a5d288ba55c03a10cb1b2dd481',
 '73628c6d02ed8f6134d9752cd7b83c2a',
 '736dca37c6d52d16556556bdd7d208ff',
 '73745cfd1447d2cb71537b662d59b3b8',
 '73adddab7cd7e4f606280f98c137656a',
 '73d6d096aaef87398a0321fc1acc5a54',
 '742b5d98b8903f6f6a0af740ddd60f2c',
 '74e198a81e758ec637a42e8f2e856927',
 '74f833bf7c70ce8c3f820f725c213e1c',
 '75020ffff57f14ba95e2562980ae510f',
 '752c0993c4993edea8eac33fda648244',
 '7533138abe254f5d3856101e4a21e5f2',
 '756fc608f67478946b31c752681f27be',
 '7622da48f027d5659a0d7b0a43597354',
 '7644fdc557b95c452791b3c1791efc08',
 '76d85afd545b8fc877273a68455675c1',
 '779078ac80552fa400b11c285d16e4fa',
 '77b8e495f75bbdf52e3a29bc46188eef',
 '7813842ae95e8c497fc0233232ae815a',
 '791d454dd290baaf30d599c6183d7489',
 '793c05f561c41e8fb6599c92be8d0afd',
 '79563470c891926bb9507d1ad1ff661d',
 '798738fb83403d78d10892ac46cf8065',
 '7a4df5d8cff4090e541401a20a22bb80',
 '7a9d4c7f9b068337875b95465330f2fc',
 '7aec7711c4f60453a59bf2f85d18187f',
 '7b417e4ab50fe706033d4fe21c659f3b',
 '7b862ac7558f536ca1c6f388f21d22d5',
 '7c48bf2308168ce82b8e622eb9dd8627',
 '7c496cea7613c2efe6033e93e573347f',
 '7d576f29bdf44b7857414baff1c788b1',
 '7dfff541b2a848ecb18ceb83d02bfa6a',
 '7e6bd960caf2346257183fd4b6079a65',
 '7ecb6c38b166531663fdecce49dc1a6f',
 '7fd4b0e047195ca197c3660772a8d8c0',
 '801bda1bc87e8484430a1ad75f51f128',
 '8040bd2eb4b6e7cfcda94f1ccdcc703d',
 '8076135356d195170fe9f8d5698182c4',
 '809a282bbd5dbcabb6f2f724fca862ec',
 '80f0181edc2f4a5bd3384a3c39a83cee',
 '80fd1b0b81771253d43532f41d575d39',
 '816e9ea5a585767bf637afdfb6d536ed',
 '81997644995458a01126899a96832353',
 '81b7c7bbc8ec003eeb67d87441a6a148',
 '82492ccd735c628d8a98d08d7ffbe501',
 '8256266a3e79c5c11593977b92fe7b1a',
 '8298521946fcd8c9f8b984aad6176694',
 '834550696228970ef03d30419db216e1',
 '8347204e1ae41b2ad30899fa41a0a889',
 '842784b3b697f1dbb51781a20352709a',
 '845f40bea2ead3894b6d95b621e108c0',
 '84b8ba39037606b7b30a39d02e9e4154',
 '858f8fbff9d717450f931fc6e9d15029',
 '85a22eb264ad44ff56c4955a66876fed',
 '85e05c3c9aa9834518f35d4f286014be',
 '85fc293d3e0bf416c547c15d991e096a',
 '8603de8fb5551ed7faf81d2a31b8bf0e',
 '869997fbe01f39d184956b5c6bccfdbe',
 '869eb48662057e0341d47dae5334b693',
 '86f0bcd9b426a2c1022ae317c7f27be6',
 '870a3cfbe4dab0f499a636a9fdeef87d',
 '876ac30251a0518e1fd87b6ec049df00',
 '87ae60ef8b08ae0e5f903cacb53a6904',
 '896fbd78a9ef3839b34b893f48f6bc67',
 '897b4da63b6edde1a33a9fb7caf1dd10',
 '8a20e2954602a0738f264299255fd5af',
 '8ab4ca9525e1f61c67972a13885d3b96',
 '8ac55ad4ce4706e06f7284f61746503a',
 '8ad27f298f11ab1248784468b3fa24e0',
 '8ae36ddb0c9660dabf5341488efb2a30',
 '8b08f0e729f58529ed03e763270f78d5',
 '8b564962527dd053cfc85c8fc98ad1df',
 '8c0ba0ee5bf1417ede40de0a3621f727',
 '8c6e16dc21c114e69bdf0d21386241eb',
 '8c8527960c6b98fe66936cff2603d394',
 '8cacf6d8c088e18ca96ee6d5a138461b',
 '8d4c637f1accf7a88a4555f02741e606',
 '8d6342c5d498f0042ad00193ce3038c8',
 '8d7e1e66103b85e9ab12cb65dafdf0e3',
 '8db43b1e3642a3227063d2517b63ecbe',
 '8e1e331cb2701fc82849ab614e8ff240',
 '8e24261a7e58791d10cb1bf9da94df5c',
 '8e4090f70c05cc129247bc0edc095dbd',
 '8e96b092573364fa542b5c5fb3a9d9a3',
 '8eeaa67e826a9308e63f4436bf00a8f2',
 '90ab3e7d52544ec7bc3363c82689965f',
 '90e258ad907d8401c4f1107ea9e55f1b',
 '90eaac01afdf4e531a70ad869e092c75',
 '91427fef1ca1431d3d86d7bcd0b51ebc',
 '91663de20f19686d62e4dbc0087fcf62',
 '9192399976bb077688f5cf72fc8ab37b',
 '9231cd28d094660487390045fec25a3b',
 '92a195ed387f8e7f9151eae7a7ec13f0',
 '92acd9b1e9af0117eee9aa972e0a4841',
 '92d731517f17c26f16182d45498c4c3d',
 '92fca7ed7b7df4695007bd7f227e3333',
 '930f7f40db5f938e56fbc1bdcd1bb28b',
 '93274b931b5771bd02154c9b716168ba',
 '9380c59012c11f49c549ef8dffef1367',
 '93881917b8e0f2bf11eec7abbbfe43ec',
 '93942353ebd22541194b59e590c0d7de',
 '940018724d5c0c1847f642dc1d8d0ea2',
 '947e9c6bfd83a06953c420ef92d3da6e',
 '94aa3ae1cb5c1c152c6cc757b68bb659',
 '94bce2ab6f38b41d29ebbd9d755677bf',
 '95251874fe384d74df990ccb85bea4ab',
 '9566b36fbba7756a79b5d2cba4e058d9',
 '95e6053477d7169c64e6a34a3e329cb7',
 '96e78a16640bdff7370dd73cb821fc01',
 '9710f97e7fb3ccd742ef8b5270d8d78f',
 '974f9f87a3bad01b2ac72fe987505e9b',
 '97b22dcad89f4916db427544e655d1b2',
 '97cf031e8c5bf37a0b310c07800e323a',
 '983e16bfbe23e60f23a6fcb9c4792204',
 '98fe01bc254b759c1f2c11d77c2891d5',
 '996316cf1b7d0bf4a95a9b5f81d7f22a',
 '998b90bcfc77ff711912c1c14dcff885',
 '99b492e774feb838a15101dc48ecb6f0',
 '9a209e12ca9ee385ad1ce1510ecfd6fc',
 '9a31fd9d697e9670777501f720773fd9',
 '9a7e2fda18922ba60aba4f140aead4dd',
 '9a8fb2a3a77dab1c301506cd5af2e845',
 '9abe82df39e950e1e0c1a5969e22571e',
 '9b932dca249f9971b86dde2f2d7ad412',
 '9b95554e4a79777fcb0168932c4a9522',
 '9bc5c73ed95bec088ff04d924946fa45',
 '9bd5312d12f48b04a460f702baff3d8c',
 '9be3c9722389548409bf4cb39d07e347',
 '9c2e92a11614b3b94ef257a4eb8540d7',
 '9c77f06d1dbb94007e708e9aba680a03',
 '9cb560230b18aed833770219fd165e16',
 '9d4369173adc91c56c54ebba6712e732',
 '9d4e334ddde795cd4fbee24dc4b68cfe',
 '9e99d220ca1057d22b317d36cf203620',
 '9eb45b0aa6ff6baf71a20c68414f8089',
 '9f24a452d2f08d94503f8755cc845362',
 '9f3458f0433d4cfa472f4682654b8d49',
 'a0141c1141d9406b48466fe4d1492bf4',
 'a027b795d174ac4c8c7fd853838b5744',
 'a0c1632c3bd45c48bed924a7dae3a664',
 'a0c1b0545665f839199e53177bc639f7',
 'a0e71b06151dd529dd0d71f578cd3457',
 'a112ffd9157da040b7951b8bb6bb2fba',
 'a144aa25d9d14f25ee9f3ec4118e5517',
 'a20244bef3bafb6f4d37e3603539336d',
 'a229af912d66e534353b1fa59daef44b',
 'a2621d414c9c28d85816bbc9f2e8980d',
 'a2ac6dad85cf8af5b0afb510a240fe8c',
 'a2bcbea8668a0d93334cf7f7fafe921d',
 'a2dd87f10cd0b3cdb73c6ba52e333250',
 'a327b5ecc65060cc462211724d715367',
 'a3777b94ef07749f031ade4ae824ddb2',
 'a37c3175caa4465852b788987ca46d1a',
 'a3b14686446d3401d67a3421891c34a3',
 'a3beebf1efa956ba70cf01a80c483367',
 'a3ef7e4271c9088cf2d3de8305ef2355',
 'a4f71a0d584883f990018a219bb7dfb4',
 'a536059a071793ef05e7e63cbac9d50e',
 'a59c87e726e3c78e26769a422a140bd3',
 'a68ce1686d536ca72bd2dadc4b8671e5',
 'a69ba794cc7deb415c3e15a0a3877e69',
 'a6d4e95420d65bd5f299dc95d3493e0d',
 'a6f980db92567852107fe54fa64726f2',
 'a7e225997eea4fd0df0db35b52bd9d0e',
 'a805d7a514bcde0719f99ddf2a3bb31d',
 'a84212c880e5635e2a0888ba25c027c7',
 'a89abace0dcc01eeb267a9660b5ac126',
 'a8ebe927b1b85cc950bba001cac770f7',
 'a91e25d9e242b0545cddf83a2bb46954',
 'a91fed0c79559403d648c1161a2d8500',
 'a9cc8ce28b99a1cc075cb04ab19010c7',
 'aaab15da689073f8f9aa978a390a69d1',
 'aaf3ed5d59c660ed5b94eb2dd4103ea0',
 'ab46182a322cb6dc83f4138d4e5cd73f',
 'abc371fa4448846ac98855c256ab235f',
 'abfacef50a27d7cea3f2c7aa60c08245',
 'ac446e82125c862fbe4c638d69f807bb',
 'ad0f5b61c49281e7ccac5a986968f347',
 'ad9a8214948a5bbd4fa03af2ea598a20',
 'adba6d04acdb64b6df4751a0e639dfd9',

In [65]:
ord_miss = orders[orders["order_id"].isin(order_missing)]

ord_miss["order_status"].value_counts()

order_status
unavailable    603
canceled       164
created          5
invoiced         2
shipped          1
Name: count, dtype: int64

In [66]:
order_rows = data["order_items"]["order_id"].value_counts()
order_rows

order_id
8272b63d03f5f79c56e9e4120aec44ef    21
1b15974a0141d54e36626dca3fdc731a    20
ab14fdcfbe524636d65ee38360e22ce8    20
428a2f660dc84138d969ccd69a0ab6d5    15
9ef13efd6949e4573a18964dd1bbe7f5    15
                                    ..
ffe73fc1d73e03fdb50e63903ddfe882     1
ffe8851012fcdaf83de7b595fd5154b3     1
ffea20c7630343a6cd9e09858c1295cd     1
ffea406a848c8afe4dec22bf6290ba00     1
fffe41c64501cc87c801fd61db3f6244     1
Name: count, Length: 98666, dtype: int64

In [67]:
order_rows[order_rows > 1].sum()

np.int64(23787)

In [68]:
data["order_items"]["price"].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [69]:
data["order_items"]["freight_value"].describe()

count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [70]:
data["order_items"]["shipping_limit_date"] = pd.to_datetime(
    data["order_items"]["shipping_limit_date"],
    errors="coerce"
)

data["reviews"]["review_creation_date"] = pd.to_datetime(
    data["reviews"]["review_creation_date"],
    errors="coerce"
)

data["reviews"]["review_answer_timestamp"] = pd.to_datetime(
    data["reviews"]["review_answer_timestamp"],
    errors="coerce"
)

In [71]:
for name, df in data.items():
    print("_"*100)
    print(name)
    
    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("\nMissing values:")
    print(df.isnull().sum())
    print(df.dtypes)
    
    print("\nDuplicate rows:", df.duplicated().sum())

____________________________________________________________________________________________________
orders
Rows: 99441
Columns: 8

Missing values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
order_items
Rows: 112650
Columns: 7

Missing values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
order_id                       object
order_item_id                   int64
product_id                     object
seller_id                      object
shipping_limit_date    datetime64[ns]
price                         float64
freight_value                 float64
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
customers
Rows: 99441
Columns: 5

Missing values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
products
Rows: 32951
Columns: 9

Missing values:
product_id                      0
product_category_name           0
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
sellers
Rows: 3095
Columns: 4

Missing values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
reviews
Rows: 99224
Columns: 7

Missing values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
review_id                          object
order_id                           object
review_score                        int64
review_comment_title               object
review_comment_message             object
review_creation_date       datetime64[ns]
review_answer_timestamp    datetime64[ns]
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
payments
Rows: 103886
Columns: 5

Missing values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
category_translation
Rows: 71
Columns: 2

Missing values:
product_category_name            0
product_category_name_english    0
dtype: int64
product_category_name            object
product_category_name_english    object
dtype: object

Duplicate rows: 0
____________________________________________________________________________________________________
geolocation
Rows: 1000163
Columns: 5

Missing values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

Duplicate rows: 261831

In [72]:
data["orders"].dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
dtype: object

In [73]:
%pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in C:\Users\Gurnoor Singh\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.0.52)
Requirement already satisfied: psycopg2-binary in C:\Users\Gurnoor Singh\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.9.12)
Requirement already satisfied: greenlet>=1 in C:\Users\Gurnoor Singh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\Gurnoor Singh\AppData\Local\Programs\Python\Python312\Lib\site-packages (from sqlalchemy) (4.13.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [74]:
import sqlalchemy
import psycopg2

print("SQLAlchemy:", sqlalchemy.__version__)
print("PostgreSQL driver: OK")

SQLAlchemy: 2.0.52
PostgreSQL driver: OK

In [75]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:YOUR_PASSWORD@localhost:5433/Olist"
)

print("Connection created")

Connection created

In [76]:
with engine.connect() as conn:
    print("PostgreSQL connection successful!")

PostgreSQL connection successful!

In [78]:
table_names = {
    "orders": "orders_clean_python",
    "order_items": "order_items_clean_python",
    "customers": "customers_clean_python",
    "products": "products_clean_python",
    "sellers": "sellers_clean_python",
    "reviews": "reviews_clean_python",
    "payments": "payments_clean_python",
    "category_translation": "category_translation_clean_python",
    "geolocation": "geolocation_clean_python"
}

for dataframe_name , sql_table_name in table_names.items():
    data[dataframe_name].to_sql(
        sql_table_name,
        engine,
        if_exists = "replace",
        index = False
    )

print(f"{sql_table_name} loaded : {data[dataframe_name].shape}")

geolocation_clean_python loaded : (1000163, 5)